### ISSUE TITLE
Could not resolve metadata for contract at 0x3ec75369c5BE84e04705B4EFe44cA10241e76Bcd     at fetchContractMetadataFromAddress

### ISSUE THREAD

**Issue by U220053** [adrianhajdin/project_crowdfunding#56]
All the solution mentioned previously doesn't work for me ..changing to activeChainId...also i am using sepolia

**Comment by bghad1** [comment]
Hi
Suggest check my repo
I settled it up on Sepolia too and is working.

I stated about it on Issue 55

**Comment by U220053** [comment]
hi @bghad1 Issue #55 contains the whole project link ...but specifically how do I resolve the error which I mentioned.

**Comment by U220053** [comment]
Also @bghad1 in .env.example what is the PROJECT ID ?where do I get it from ...actually i am complete beginner so kindly help

**Comment by BahadorGh** [comment]
Hey @U220053 
.env is a file, for security reasons. But in case of testing, you don't need it.
You can easily set your rpc url(ex: infura rpc) and private key, in hardhat.config.js

**Comment by U220053** [comment]
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:13102:46
    at http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:2032:11
    at http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:2009:11
    at http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:2101:13
    at http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:2032:11
    at http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:2009:11
    at http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:2101:13
    at http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:2558:11
    at http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:5534:11
    at http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:6382:11
    at Provider (http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:1824:15)
    at Provider (http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:1824:15)
    at Provider (http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:1824:15)
    at $cf1ac5d9fe0e8206$export$badac9ada3a0bdf9 (http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:2545:11)
    at $6cc32821e9371a1c$export$d9b273488cd8ce6f (http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:5476:11)
    at Provider (http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:1824:15)
    at $d08ef79370b62062$export$e44a253a59704894 (http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:6346:11)
    at ConnectedWalletDetails (http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:7594:22)
    at ThemeProvider2 (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:13149:23)
    at ConnectWallet (http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:8122:24)
    at button
    at CustomButton (http://localhost:5174/src/components/CustomButton.jsx:19:3)
    at div
    at div
    at Navbar (http://localhost:5174/src/components/Navbar.jsx:26:20)
    at div
    at div
    at App
    at StateContextProvider (http://localhost:5174/src/context/index.jsx:27:3)
    at Router (http://localhost:5174/node_modules/.vite/deps/react-router-dom.js?v=3fbb81e1:3580:15)
    at BrowserRouter (http://localhost:5174/node_modules/.vite/deps/react-router-dom.js?v=3fbb81e1:4042:5)
    at ThirdwebAuthProvider (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:9499:5)
    at WrappedThirdwebSDKProvider (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:9692:5)
    at QueryClientProvider (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:2994:3)
    at QueryClientProviderWithDefault (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:8710:5)
    at ThirdwebConnectedWalletProvider (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:9618:5)
    at ThirdwebConfigProvider (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:9597:5)
    at ThirdwebSDKProvider (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:9783:5)
    at ThirdwebSDKProviderWrapper (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:9916:5)
    at ThirdwebWalletProvider (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:8795:58)
    at ThirdwebProviderCore (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:9846:5)
    at ThemeProvider2 (http://localhost:5174/node_modules/.vite/deps/chunk-XWBPS765.js?v=3fbb81e1:13149:23)
    at WalletUIStatesProvider (http://localhost:5174/node_modules/.vite/deps/chunk-VKAU77NA.js?v=3fbb81e1:4727:81)
    at ThirdwebProvider (http://localhost:5174/node_modules/.vite/deps/@thirdweb-dev_react.js?v=3fbb81e1:9134:5)
printWarning @ react-dom.development.js:86
3index.ts:269 Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getCampaigns()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (index.ts:269:28)
    at Logger.throwError (index.ts:281:20)
    at Interface.decodeFunctionResult (interface.ts:427:23)
    at Contract.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:13:1)   getting this error ..I tried using your code and changing the env file and following the steps as mentioned

**Comment by U220053** [comment]
![Screenshot (721)](https://github.com/adrianhajdin/project_crowdfunding/assets/78076309/0517e262-fc68-414b-b2b4-1113fc528cfe)
![Screenshot (719)](https://github.com/adrianhajdin/project_crowdfunding/assets/78076309/5ca0547a-d551-4c6c-8e07-52411fa92893)
![Screenshot (720)](https://github.com/adrianhajdin/project_crowdfunding/assets/78076309/a3e9fba9-7112-4cd0-9b39-212d1beea275)

**Comment by U220053** [comment]
@bghad1

**Comment by BahadorGh** [comment]
> ![Screenshot (721)](https://user-images.githubusercontent.com/78076309/252132444-0517e262-fc68-414b-b2b4-1113fc528cfe.png) ![Screenshot (719)](https://user-images.githubusercontent.com/78076309/252132467-5ca0547a-d551-4c6c-8e07-52411fa92893.png) ![Screenshot (720)](https://user-images.githubusercontent.com/78076309/252132469-a3e9fba9-7112-4cd0-9b39-212d1beea275.png)

I'm sure the issue was solved in my latest push.
By the way, to solve the error of <button> cannot appear ..., you have to fix it in Navbar.jsx component:

Place this function before returning html elements:
`  
const handleUserAccount = () => {
    return <ConnectWallet /> 
  }
`

And after that, replace this code with prior code:
`
      <div className="sm:flex hidden flex-row justify-end gap-4">
        <CustomButton 
          btnType="button"
          title={!address ? 'Connect' : handleUserAccount() }
          styles={!address ? 'bg-[#1dc071]' : '' /*'bg-[#8c6dfd]'*/ }
          handleClick={() => {
            if(address) navigate('create-campaign')
            else connect()
          }}
        />
`

Please let me know if it solved.

**Comment by BahadorGh** [comment]
Also about the another problem you faced(call revert exception), did you deploy your contract?

**Comment by U220053** [comment]
@BahadorGh yes I deployed without project id on hardhat network ...where do I get project Id from as mentioned in env.example

**Comment by U220053** [comment]
import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom';

import { useStateContext } from '../context';
import { CustomButton } from './';
import { logo, menu, search, thirdweb } from '../assets';
import { navlinks } from '../constants';
import { ConnectWallet } from '@thirdweb-dev/react';

const Navbar = () => {
  const navigate = useNavigate();
  const [isActive, setIsActive] = useState('dashboard');
  const [toggleDrawer, setToggleDrawer] = useState(false);
  const { connect, address } = useStateContext();

  const handleUserAccount = () => {
    return <ConnectWallet /> 
  }

  return (
    <div className="flex md:flex-row flex-col-reverse justify-between mb-[35px] gap-6">
      <div className="lg:flex-1 flex flex-row max-w-[458px] py-2 pl-4 pr-2 h-[52px] bg-[#1c1c24] rounded-[100px]">
        <input type="text" placeholder="Search for campaigns" className="flex w-full font-epilogue font-normal text-[14px] placeholder:text-[#4b5264] text-white bg-transparent outline-none" />
        
        <div className="w-[72px] h-full rounded-[20px] bg-[#4acd8d] flex justify-center items-center cursor-pointer">
          <img src={search} alt="search" className="w-[15px] h-[15px] object-contain"/>
        </div>
      </div>

      <div className="sm:flex hidden flex-row justify-end gap-4">
        <CustomButton 
          btnType="button"
          title={!address ? 'Connect' : handleUserAccount() }
          styles={!address ? 'bg-[#1dc071]' : '' /*'bg-[#8c6dfd]'*/ }
          handleClick={() => {
            if(address) navigate('create-campaign')
            else connect()
          }}
        />

        <Link to="/profile">
          <div className="w-[52px] h-[52px] rounded-full bg-[#2c2f32] flex justify-center items-center cursor-pointer">
            <img src={thirdweb} alt="user" className="w-[60%] h-[60%] object-contain" />
          </div>
        </Link>
      </div>

      {/* Small screen navigation */}
        <div className="sm:hidden flex justify-between items-center relative">
        <div className="w-[40px] h-[40px] rounded-[10px] bg-[#2c2f32] flex justify-center items-center cursor-pointer">
            <img src={logo} alt="user" className="w-[60%] h-[60%] object-contain" />
          </div>

          <img 
            src={menu}
            alt="menu"
            className="w-[34px] h-[34px] object-contain cursor-pointer"
            onClick={() => setToggleDrawer((prev) => !prev)}
          />

          <div className={`absolute top-[60px] right-0 left-0 bg-[#1c1c24] z-10 shadow-secondary py-4 ${!toggleDrawer ? '-translate-y-[100vh]' : 'translate-y-0'} transition-all duration-700`}>
            <ul className="mb-4">
              {navlinks.map((link) => (
                <li
                  key={link.name}
                  className={`flex p-4 ${isActive === link.name && 'bg-[#3a3a43]'}`}
                  onClick={() => {
                    setIsActive(link.name);
                    setToggleDrawer(false);
                    navigate(link.link);
                  }}
                >
                  <img 
                    src={link.imgUrl}
                    alt={link.name}
                    className={`w-[24px] h-[24px] object-contain ${isActive === link.name ? 'grayscale-0' : 'grayscale'}`}
                  />
                  <p className={`ml-[20px] font-epilogue font-semibold text-[14px] ${isActive === link.name ? 'text-[#1dc071]' : 'text-[#808191]'}`}>
                    {link.name}
                  </p>
                </li>
              ))}
            </ul>

            <div className="flex mx-4">
            <CustomButton 
              btnType="button"
              title={address ? 'Create aaa campaign' : 'Connect'}
              styles={address ? 'bg-[#1dc071]' : 'bg-[#8c6dfd]'}
              handleClick={() => {
                if(address) navigate('create-campaign')
                else connect();
              }}
            />
            </div>
          </div>
        </div>
    </div>
  )
}

export default Navbar


Code for navbar ...the changes you told already present in code still no affect @bghad1 @BahadorGh

**Comment by U220053** [comment]
The changes in navbar is already in the code of navbar still no affect

**Comment by BahadorGh** [comment]
> @BahadorGh yes I deployed without project id on hardhat network ...where do I get project Id from as mentioned in env.example

You can sign up in Infura.io and create a project there to get project id

**Comment by Mosqu1to3zZ** [comment]
Hey bro do like this can solve problem .
```
root.render(
  <ThirdwebProvider activeChain="goerli" clientId="5"> 
    <Router>
      <StateContextProvider>
        <App />
      </StateContextProvider>
    </Router>
  </ThirdwebProvider> 
```
