### ISSUE TITLE
How do I resolve this issue?

### ISSUE THREAD

**Issue by sharifahalawiyah** [adrianhajdin/project_crowdfunding#59]
I have a problem when trying to create a campaign. The error is as below:

Uncaught (in promise) Error: invalid BigNumber string (argument="value", value="2023-07-20", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (index.ts:269:28)
    at Logger.throwError (index.ts:281:20)
    at Logger.throwArgumentError (index.ts:285:21)
    at BigNumber.from (bignumber.ts:238:27)
    at NumberCoder.encode (number.ts:25:27)
    at array.ts:71:19
    at Array.forEach (<anonymous>)
    at pack (array.ts:54:12)
    at TupleCoder.encode (tuple.ts:54:16)
    at AbiCoder.encode (abi-coder.ts:111:15)
    
 Would really appreciate the help. Thank you :)

**Comment by BotRavat** [comment]
May be you are missing toString() function call .  Go to client->src->context->index.js file in the getDonations() function check this line   donations:ethers.utils.formatEther(donations[1][i].toString())
