### ISSUE TITLE
query.ts:446 Error: Could not resolve metadata for contract at 0xF2819312c49b121711E127cf8B7bf4CFC715B664     at fetchContractMetadataFromAddress (contract-publisher-d55c8d8a.browser.esm.js:4362:13)

### ISSUE THREAD

**Issue by GauravDuseja1** [adrianhajdin/project_crowdfunding#60]
Please Help

**Comment by BahadorGh** [comment]
It seems your contract address might be wrong.

**Comment by salmankhan321** [comment]
same problem for me, I have use correct address but still not working

**Comment by BahadorGh** [comment]
@salmankhan321 @GauravDuseja1 I guess you are missing activeChainId in your main.js file

**Comment by Prash766** [comment]
i am facing the similar issue , have used the correct address but still showing me the same error .
query.ts:446 Error: Could not resolve metadata for contract at 0xE25c92898B4621Fc264DA62C46Fbc6e06fBdA0aB
    at fetchContractMetadataFromAddress (contract-publisher-d55c8d8a.browser.esm.js:4362:13)
    
    
    here is the code for main.jsx file
    import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter as Router } from 'react-router-dom';
import { ChainId, ThirdwebProvider } from '@thirdweb-dev/react';

import { StateContextProvider } from './context';
import App from './App';
import './index.css';

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
  <ThirdwebProvider activeChainChainId={ChainId.Goerli}> 
    <Router>
      <StateContextProvider>
        <App />
      </StateContextProvider>
    </Router>
  </ThirdwebProvider> 
)

please help!!!

**Comment by Prash766** [comment]
i am facing the similar issue , have used the correct address but still showing me the same error .
query.ts:446 Error: Could not resolve metadata for contract at 0xE25c92898B4621Fc264DA62C46Fbc6e06fBdA0aB
at fetchContractMetadataFromAddress (contract-publisher-d55c8d8a.browser.esm.js:4362:13)


import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter as Router } from 'react-router-dom';
import { ChainId, ThirdwebProvider } from '@thirdweb-dev/react';

import { StateContextProvider } from './context';
import App from './App';
import './index.css';

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
<ThirdwebProvider activeChainChainId={ChainId.Goerli}> 
    <Router>
      <StateContextProvider>
        <App />
      </StateContextProvider>
    </Router>
  </ThirdwebProvider> 






)

please help!!!

**Comment by salmankhan321** [comment]
go to client > source > main.jsx file
and replace with this code

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
  <ThirdwebProvider activeChain={ChainId.Goerli}>
    <Router>
      <StateContextProvider>
        <App />
      </StateContextProvider>
    </Router>
  </ThirdwebProvider>
)

**Comment by Prash766** [comment]
Thankyou for helping me 😀😀

**Comment by Mosqu1to3zZ** [comment]
Hey bro , do like this can solve problem
root.render(
  <ThirdwebProvider activeChain="goerli" clientId="5"> 
    <Router>
      <StateContextProvider>
        <App />
      </StateContextProvider>
    </Router>
  </ThirdwebProvider>

**Comment by emirbektas** [comment]
I still get this error. I'm using Sepolia instead of goerli. Here's my code

```
import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import { ChainId, ThirdwebProvider } from "@thirdweb-dev/react";
import { Sepolia } from "@thirdweb-dev/chains";
import "./styles/globals.css";
import { StateContextProvider } from "./context";

const container = document.getElementById("root");
const root = createRoot(container);
root.render(
  <React.StrictMode>
    <ThirdwebProvider
      activeChain={ChainId.Sepolia}
      clientId="a82c3a6dcea35d5623fc769446c4fdf3"
    >
      <StateContextProvider>
        <App />
      </StateContextProvider>
    </ThirdwebProvider>
  </React.StrictMode>
);
```

**Comment by abhii9922** [comment]
import { Sepolia } from "@thirdweb-dev/chains";
  <ThirdwebProvider activeChain={Sepolia}
  
  
  do it in this way, It worked for me
