### ISSUE TITLE
Thirdweb API Key required after August 2023 to complete this tutorial.

### ISSUE THREAD

**Issue by hiddenciphers** [adrianhajdin/project_crowdfunding#72]
Thirdweb API Key required after August 2023.

https://portal.thirdweb.com/api-keys

**Comment by vanshverma721** [comment]
how to use brother can u elaborate plzzz my project is not working now, when i have made it full its working but now when i have opened it after a long time its not working??

**Comment by alisonborba** [comment]
Hey @vanshverma721, I've created an [MR-74](https://github.com/adrianhajdin/project_crowdfunding/pull/74) fixing it. Please take a look and fix it on your environment.

**Comment by Cyber01World** [comment]
> Hey @vanshverma721, I've created an [MR-74](https://github.com/adrianhajdin/project_crowdfunding/pull/74) fixing it. Please take a look and fix it on your environment.

I did that but still i m unable to run it. these are the error i m getting. 

TypeError: Cannot read properties of undefined (reading 'call')
    at Object.mutationFn (index-dd0e7329.esm.js:1172:23)
    at Object.fn (mutation.ts:177:31)
    at run (retryer.ts:145:31)
    at createRetryer (retryer.ts:201:5)
    at executeMutation (mutation.ts:172:22)
    at Mutation.execute (mutation.ts:214:26)
    at async publishCampaign (index.jsx:28:20)
    at async CreateCampaign.jsx:33:9
execute @ mutation.ts:250

contract call failure TypeError: Cannot read properties of undefined (reading 'call')
    at Object.mutationFn (index-dd0e7329.esm.js:1172:23)
    at Object.fn (mutation.ts:177:31)
    at run (retryer.ts:145:31)
    at createRetryer (retryer.ts:201:5)
    at executeMutation (mutation.ts:172:22)
    at Mutation.execute (mutation.ts:214:26)
    at async publishCampaign (index.jsx:28:20)
    at async CreateCampaign.jsx:33:9

note- i cloned the repo and runned npm run , changed the contract address and added the apikey. now what else should i do ?

**Comment by alisonborba** [comment]
Hey @Cyber01World ! Are you receiving this error before creating the campaign: `query.ts:446 Error: Could not fetch bytecode for contract at 0x3cEeEbd92D12345678901234567890 on chain 1, double check that the address and chainId are correct.` ?

I'm not sure what's happening with your app, but I would suggest you remove the `node_module` and `package-lock.json`, use the latest node LTS version (20), install the packages again, and then try to create a campaign again.
