### ISSUE TITLE
Cannot destructure property 'existsSync' of 'require_empty(...)' as it is null.

### ISSUE THREAD

**Issue by lantianlaoli** [adrianhajdin/project_crowdfunding#77]
```
previous-map.js:4  Uncaught TypeError: Cannot destructure property 'existsSync' of 'require_empty(...)' as it is null.
    at node_modules/postcss/lib/previous-map.js (previous-map.js:4:7)
    at __require2 (chunk-GN3OLCG2.js?v=c58f3a24:19:50)
    at node_modules/postcss/lib/input.js (input.js:10:19)
    at __require2 (chunk-GN3OLCG2.js?v=c58f3a24:19:50)
    at input.js:248:1
```

**Comment by lantianlaoli** [comment]
[import Input from 'postcss/lib/input'](url)
 error at FromField.jsx!!! care of don't not auto import it !!!
